"""
Статические списки брендов шин и дисков
Данные взяты с сайта 4tochki.ru
"""

TIRE_BRANDS = [
    "Любой",
    "Altenzo",
    "Antares",
    "Aoteli",
    "Aplus",
    "Arivo",
    "Attar",
    "Bars",
    "Barum",
    "Belshina",
    "BFGoodrich",
    "Boto",
    "Bridgestone",
    "Cachland",
    "Comforser",
    "Compasal",
    "Continental",
    "Contyre",
    "Cooper",
    "Cordiant",
    "Doublestar",
    "Dunlop",
    "Dunlop JP",
    "Eca-Tecar",
    "Evergreen",
    "Fortune",
    "Forward",
    "Fulda",
    "General Tire",
    "Ginell",
    "Gislaved",
    "Goodride",
    "Goodyear",
    "GT Radial",
    "Haida",
    "Hankook",
    "Hankook Laufenn",
    "HiFly",
    "Ikon",
    "iLink",
    "Kama",
    "Kapsen",
    "Kleber",
    "Kormoran",
    "Kumho",
    "Landsail",
    "Landspider",
    "Lassa",
    "LingLong",
    "LingLong Leao",
    "Marshal",
    "Massimo",
    "Matador",
    "Maxxis",
    "Mazzini",
    "Michelin",
    "Mickey Thompson",
    "Mirage",
    "Nankang",
    "Nereus",
    "Nexen",
    "Next",
    "Nitto",
    "Nokian Tyres",
    "Nordman",
    "NorTec",
    "Onvx",
    "Ovation",
    "Pirelli",
    "Pirelli Amtel",
    "Pirelli Formula",
    "Powertrac",
    "Rapid",
    "Roadcruza",
    "Roadmarch",
    "Roadstone",
    "RoTaLLa",
    "Royal Black",
    "Sailun",
    "Sailun RoadX",
    "Sava",
    "Sunfull",
    "Sunny",
    "Three-A",
    "Tigar",
    "Torero",
    "Torque",
    "Toyo",
    "Tracmax",
    "Triangle",
    "Tunga",
    "Unigrip",
    "Viatti",
    "Vittos",
    "Voltyre",
    "Vredestein",
    "Wanda",
    "West Lake",
    "Windforce",
    "Yokohama",
    "Zeta",
    "Алтайшина",
    "Кировский Ш3"
]

# TODO: Добавить список брендов дисков
DISK_BRANDS = [
    "Любой",
    "Replay",
    "LegeArtis",
    "СКАД",
    "K&K",
    "LS Wheels",
    "Tech Line",
    "Trebl",
    "Neo",
    "Off-Road Wheels",
]
